version: '3'

services:
  db:
    image: mariadb:10
    hostname: mariadb-controlpage
    container_name: controlpage_mariadb
    restart: unless-stopped
    environment:
      - MARIADB_ROOT_PASSWORD=DYxH2NgFh7A55BEqUYAMGPxPxLv6fD3DeCa487LWMD
    volumes:
      - mariadb_data:/var/lib/mysql

  adminer:
    image: adminer
    hostname: mariadb-controlpage-adminer
    container_name: controlpage_adminer
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - 8080:8080

  frontend:
    image: gitlab-registry.fischerserver.eu/controlpage/controlpage-releases/frontend:latest
    container_name: controlpage_frontend
    hostname: controlpage-frontend
    restart: on-failure
    depends_on:
      - backend
    ports:
      - 8008:80

  backend:
    image: gitlab-registry.fischerserver.eu/controlpage/controlpage-releases/backend:latest
    container_name: controlpage_backend
    hostname: controlpage-backend
    depends_on:
      - db
    ports:
      - 42000:42000
    environment:
      - DB_HOST=mariadb-controlpage

volumes:
  mariadb_data:
